services:
  canvas:
    image: ghcr.io/tesselation-studios/canvas:latest
    build: .
    container_name: canvas
    restart: unless-stopped
    environment:
      - CANVAS_TOKEN=${CANVAS_TOKEN}
    volumes:
      - canvas_data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.canvas.rule=Host(`canvas.wodinga.studio`)"
      - "traefik.http.routers.canvas.entrypoints=websecure"
      - "traefik.http.services.canvas.loadbalancer.server.port=5000"

volumes:
  canvas_data:

networks:
  traefik:
    external: true